# Generated by Django 5.1.2 on 2025-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250415_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='genre',
            new_name='category',
        ),
    ]
