# Generated by Django 5.1.2 on 2025-04-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_genre_books_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='genre',
        ),
    ]
