# Generated by Django 5.1.2 on 2025-04-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_category_books_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
    ]
