# Generated by Django 5.1.7 on 2025-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='myapp.category'),
        ),
    ]
