# Generated by Django 5.1.7 on 2025-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
